[fabric_corrections]
# Коррекция размера отреза тканей для боковины.
# Вставьте в название ткани слово из этого списка,
# чтобы применить указанные изменения для нарезчика.
# Метод ищет эти слова в названии ткани в СБИС.
"Жаккард" = -10
"Трикотаж" = -5
"Bord" = 0

[components]
# Эти артикулы будут показываться нарезчику
showed_articles = [
    '0',
    '000',
    '807',
    '808',
    '809',
    '901',
    '902',
    '903',
    '904',
    '905',
    '906',
    '907',
    '908',
    '909',
    '911',
    '912'
]


[site]
# Настройки рабочего пространства.
# Пропишите регионы доставки через запятую внутри квадратных скобок.
regions = [
    'Краснодарский край',
    'Ростовская область',
    'Крымский полуостров',
    'Уральский автономный округ',
]

delivery_types = [
    'Самовывоз',
    "Город",
    "Край",
    "Регионы",
    "Страны"
]
streamlit_port = '8501'
flask_port = '5000'

[site.hardware]
default_printer = 'HP Ink Tank 110 series'  # Название стандартного принтера для печати гарантийных талонов
label_printer = 'Xprinter xp-370b'  # Название термопринтера для печати наклеек
backup_path = "backup"  # В эту папку будут складываться бэкапы
log_filepath = "cash/application.log"  # В этот файл будут записываться логи
tasks_cash_filepath = "cash/tasks"  # Указание пути для папки с нарядами. Там хранятся pandas-датафреймы, упакованные в .pkl
employees_cash_filepath = "cash/employees.pkl"  # Данные таблицы управления сотрудниками
current_tasks_cash_filepath = "cash/current_tasks.json"  # Данные закреплённых нарядов
database_path = 'mattress_orders.db'

[sbis]
# Данные от аккаунта СБИС. От его имени будут формироваться заявки
#login = "leartest"
login = "Харьковский_Гас_РС"
#password = "Leartest2007!"
password = "Харьковский_Гас_РС4342"

# Эти данные можно получить из раздела СБИС - Настройки - Безопасность - Подключения СБИС
#app_client_id = "1431941504152192"
app_client_id = "6545046667107472"
#app_secret = "TTLJISTWTTJKIMTITQMTM2TP"
app_secret = "JYXNGTMT8QU5SQTJDEMLXGGX"
#secret_key = "qwTLov0WOF8mgL3h8zRpcbITQxGBdY763n2tTrPYhRLviLy12agCCbyxPuuBak3IDfScRd1yX4IJJphJy1eO56L0vmCz5MIVQEMQEJXpS1QlpqlMI15Gbx"
secret_key = "VcRzvQs9JRWTXCHzeP8jFRquZqeOVL4y6o0L9zvNZJqn8ptQwuRot3skjUmItb8uSkglbWBDln0e7tJvRIze3vLo6I0bxk62T6RTdYKWA4MHatsLMaKMZm"

# Данные для корректной загрузки списка товаров
sale_point_name = "Гаспарян Роман Славикович, ИП"  # Полное название торговой точки
price_list_name = "Позиции для Telegram-бота"  # Название прайс-листа из СБИС - Бизнес - Цены
implementation_filepath = "cash/implementation.xml"  # Расположение шаблона формирования реализации в СБИС
#task_filepath = "task_cash/task.html"  # Расположение шаблона формирования задачи СБИС

# Список свойств товаров можно получить методом get_nomenclature_list() из sbis_manager.py
mattress_group_id = 2  # Товары с hierarchicalParent равным mattress_group_id считаются матрасами и добавляются в датафрейм
fabrics_group_id = 285  # Эти товары - ткани. Показываются при выборе ткани из окна заявок.
springs_group_id = 294 # Пружинные блоки.

[sbis.regalement_id_list]
# ID регламента СБИС.
wholesale = "3b9ac7d9-8ace-47c8-85b6-cf45888bab05" # Реализация матрасов
direct_sell = "f67256dd-8674-4a75-91d0-22d3494e4c13" # Розница
#order_delivery = "2c36b133-7a8a-4f69-82a6-89409c38a373"
#task = "05999956-3a78-4f91-bb80-a08b7eceb954"


[telegram]
token = "6945801898:AAF6H5if3-fLvRDm9W2CzUaGCQTVxU2iK68"
group_chat_id = '-1002167954426'
