[client]
showErrorDetails = true

# * "developer" : Проказывает настройки в меню-точечках справа вверху
# * "viewer"    : Прячет
# * "minimal"   : Показывает не всё
toolbarMode = "developer"

# Показывает странички слева
showSidebarNavigation = true

[theme]
primaryColor = "#4B58FF"  # Синий
backgroundColor = "white"

[browser]
# Растягивает страничку по ширине экрана
#layout = "wide"

[logger]
# Уровни: 'error', 'warning', 'info', 'debug'.
level = "info"
# По умолчанию: `%(asctime)s.%(msecs)03d %(message)s`
messageFormat = "%(asctime)s %(message)s"