[client]
showErrorDetails = true

# * "developer" : Проказывает настройки в меню-точечках справа вверху
# * "viewer"    : Показывает не всё
# * "minimal"   : Прячет
toolbarMode = "minimal"

# Показывает странички слева
showSidebarNavigation = false

[theme]
primaryColor = "#4B58FF"  # Синий
backgroundColor = "white"

[logger]
# Уровни: 'error', 'warning', 'info', 'debug'.
level = "info"
# По умолчанию: `%(asctime)s.%(msecs)03d %(message)s`
messageFormat = "%(asctime)s %(message)s"