[client]
showErrorDetails = true
# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# * "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# * "developer" : Show the developer options.
# * "viewer"    : Hide the developer options.
# * "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "developer"
# Controls whether the default sidebar page navigation in a multipage app is
# displayed.
# Default: true
showSidebarNavigation = true

[theme]
primaryColor = "#4B58FF"
backgroundColor = "white"

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"
# logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`
messageFormat = "%(asctime)s %(message)s"